import os

def text_to_speech(text, output_path_location="output.mp3", subtitle_path_location="output.vtt"):
    voice = "en-CA-LiamNeural"
    command = f"edge-tts --voice \"{voice}\" --text \"{text}\" --write-media \"{output_path_location}\" --write-subtitles \"{subtitle_path_location}\""
    os.system(command)

    return output_path_location, subtitle_path_location

text="As the sun rises over the bustling streets of India, a sense of excitement fills the air. Today marks the beginning of a journey—a journey from the vibrant chaos of India to the tranquil beauty of Japan. With bags packed and anticipation in the air, our traveler sets forth on this adventure, leaving behind the familiar sights and sounds of home. Boarding the flight to Japan, they embark on a voyage into the unknown, ready to embrace new experiences and immerse themselves in a foreign culture. As the plane touches down on Japanese soil, a wave of excitement washes over our traveler. Japan—the land of cherry blossoms, ancient temples, and cutting-edge technology—awaits. From the bustling streets of Tokyo, where neon lights and skyscrapers paint the skyline, to the serene countryside dotted with picturesque cherry blossom trees, Japan offers a tapestry of experiences waiting to be explored. In the heart of Tokyo, our traveler navigates through the bustling crowds of Shibuya Crossing, a whirlwind of energy and movement. Amidst the chaos, they discover moments of tranquility in the city's serene gardens and shrines, where time seems to stand still amidst the hustle and bustle. And then, there's the food—the rich tapestry of flavors and textures that define Japanese cuisine. With hesitant anticipation, our traveler takes their first bite of sushi, only to be greeted by an explosion of flavor that ignites their taste buds and leaves them craving more. Venturing beyond the city limits, our traveler finds solace in the tranquil beauty of Japan's countryside. Surrounded by rolling hills and cherry blossom trees in full bloom, they find a sense of peace and serenity unlike anything they've experienced before. As they journey through Japan, our traveler encounters the warmth and hospitality of the Japanese people, whose kindness and generosity leave a lasting impression. Whether receiving a gift from a local or sharing a meal with newfound friends, each interaction becomes a cherished memory. But as all journeys do, this one must eventually come to an end. With a heavy heart and a lifetime of memories, our traveler bids farewell to Japan, knowing that they will carry its spirit with them wherever they go. And so, as the sun sets on this chapter of their journey, our traveler looks forward to the next adventure that awaits, knowing that the memories of Japan will stay with them forever. "
audio_file, subtitle_file = text_to_speech(text)
